### ISSUE TITLE
Droplet ID must be Powered Off Error

### ISSUE THREAD

**Issue by ndalliard** [merqlove/do_snapshot#10]
When I do a backup I get:

`Droplet id: 6378264 must be Powered Off!`

Which interrupts the backup and let the droplet offline... No snapshot taken.

The command I use:

`do_snapshot -p 2 --only 6378264 -k 2 -c -m to:$TO from:       $FROM -t address:$HOST user_name:$LOGIN password:$PASSWORD port:587 -v`

When I am at the backend at DO I see, t hat the droplet is getting powered off. But it takes a while until it shows, that the droplet is offline. In the meantime the script interrupts and I have to power on it by hand.

**Comment by merqlove** [comment]
Yeah, this is DigitalOcean API bug. I can add option for checking droplet by shutdown status, instead of waiting for shutdown event. 
DigitalOcean API sometimes answers that event finished, but it still alive.

**Comment by merqlove** [comment]
Starting from version 0.4.1 you will able to use option: --stop-by-power

**Comment by ndalliard** [comment]
That works perfect. Thanks a lot!

**Comment by netickfr** [comment]
I was looking for this option ;) Thanks
