### ISSUE TITLE
Creates multiple snapshots at the same time

### ISSUE THREAD

**Issue by Zyles** [merqlove/do_snapshot#11]
Problem: Creates 5 backups at the same time instead of just 1.

I run this cron on an external machine:
```
* 6 * * 1 /usr/local/bin/do_snapshot --protocol 2 --keep 5 --digital-ocean-access-token XXXXX  &> /dev/null
```

This should run every Monday at 6, which is does.

The problem is it should only create ONE snapshot every Monday, instead it creates FIVE snapshots every Monday of the same server!

Looking at my Digitalocean snapshot control panel they all have the same timestamp.

Version 0.4.1

**Comment by merqlove** [comment]
Hmm, i will check. @Zyles thanks for report.

**Comment by merqlove** [comment]
@Zyles Just tried for test machine on DO. My suggestions for you is to use logs or Mail notifications. In this case i will can find problem if it exists. 
So for now i haven't found any problem.
Maybe you have some problem with cron? :)

```bash
$ /usr/local/bin/do_snapshot -p 2 --only=8523146 -k 5 -c -v --stop-by-power -l /Users/merqlove/.do_snapshot/cron.log

Start performing operations
Loading list of DigitalOcean droplets
Checking DigitalOcean Access Token.
Setting DigitalOcean Access Token.
Droplet id: 8523146 name: test
Preparing droplet id: 8523146 name: test to take snapshot.
Working with list of DigitalOcean droplets
Shutting down droplet.
Droplet Id: 8523146 shutting down
Start creating snapshot for droplet id: 8523146 name: test.
Wait until snapshot will be created.
Event Id: 70088969
Snapshot name: test_2015_10_31 created successfully.
Droplet id: 8523146 name: test snapshots: 1.
All operations has been finished.
```
