### ISSUE TITLE
Getting this Issue when running 

### ISSUE THREAD

**Issue by ameenhexwhale** [merqlove/do_snapshot#13]
do_snapshot --keep 10 -c
Start performing operations
Loading list of DigitalOcean droplets
Checking DigitalOcean Access Token.
undefined method `blank?' for #<String:0x007fabd40b3bc8>
/Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/adapter/digitalocean_v2.rb:98:in `block in check_keys': undefined method `blank?' for #<String:0x007fabd40b3bc8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/adapter/digitalocean_v2.rb:97:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/adapter/digitalocean_v2.rb:97:in `check_keys'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/adapter/abstract.rb:15:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/adapter.rb:15:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/adapter.rb:15:in `api'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/command.rb:95:in `api'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/command.rb:137:in `load_droplets'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/command.rb:126:in `work_with_droplets'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/command.rb:16:in `snap'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/cli.rb:156:in `snap'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/runner.rb:38:in `run_cli'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/lib/do_snapshot/runner.rb:17:in `execute!'
	from /Library/Ruby/Gems/2.0.0/gems/do_snapshot-0.6.2/bin/do_snapshot:15:in `<top (required)>'
	from /usr/local/bin/do_snapshot:23:in `load'
	from /usr/local/bin/do_snapshot:23:in `<main>'

**Comment by merqlove** [comment]
@ameenhexwhale Thanks for report. I will fix it ASAP.
It means that you don't set DO Token in your ENV or via params.
```fail DoSnapshot::NoTokenError, "You must have #{key} in environment or set it via options." if ENV[key].blank?```

**Comment by merqlove** [comment]
@ameenhexwhale Fixed.
Please check.

**Comment by ameenhexwhale** [comment]
yup now its working fine
