### ISSUE TITLE
Multiple Hashie warnings in console output

### ISSUE THREAD

**Issue by leafnode** [merqlove/do_snapshot#19]
When I run do_snapshot I get multiple warnings:

> W, [2017-06-22T15:49:37.369129 #18353]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#size defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.

It's obfuscating the output and makes it difficult to read.

Per intridea/hashie#394, it should be quite easy to silence them.

**Comment by merqlove** [comment]
@leafnode Hmm, thanks for the notice, i will add Hashie.logger override. 
Anyway seems that Barge not updated for a long time. feel free to PR port into dropletkit.

**Comment by merqlove** [comment]
Fix added, waiting for specs. Now hashie logs via our internal logger.

**Comment by merqlove** [comment]
https://github.com/merqlove/do_snapshot/releases/tag/v0.6.4
