### ISSUE TITLE
uninitialized constant ResourceKit::ResourceCollection::Forwardable

### ISSUE THREAD

**Issue by skatkov** [merqlove/do_snapshot#21]
Good day, i'm running into issues while trying to perform a snapshot backup.

- Using ruby 2.4.1, OSX
- Installed do_snapshot as a gem
- Set ENV token variable
- Execute `do_snapshot --only 53097244 -k 5 -c -v`

Result:

```
Start performing operations
Loading list of DigitalOcean droplets
uninitialized constant ResourceKit::ResourceCollection::Forwardable
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:3:in `<class:ResourceCollection>'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:2:in `<module:ResourceKit>'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:1:in `<top (required)>'
/Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/gem_ext/resource_kit.rb:19:in `<top (required)>'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter/droplet_kit.rb:4:in `require_relative'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter/droplet_kit.rb:4:in `<top (required)>'
/Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter.rb:13:in `const_defined?'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter.rb:13:in `api'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:102:in `api'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:144:in `load_droplets'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:133:in `work_with_droplets'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:21:in `snap'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/cli.rb:161:in `snap'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/runner.rb:39:in `run_cli'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/runner.rb:18:in `execute!'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/bin/do_snapshot:16:in `<top (required)>'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/bin/do_snapshot:22:in `load'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/bin/do_snapshot:22:in `<main>'
/Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:3:in `<class:ResourceCollection>': uninitialized constant ResourceKit::ResourceCollection::Forwardable (NameError)
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:2:in `<module:ResourceKit>'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:1:in `<top (required)>'
	from /Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/gem_ext/resource_kit.rb:19:in `<top (required)>'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter/droplet_kit.rb:4:in `require_relative'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter/droplet_kit.rb:4:in `<top (required)>'
	from /Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sk/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter.rb:13:in `const_defined?'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter.rb:13:in `api'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:102:in `api'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:144:in `load_droplets'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:133:in `work_with_droplets'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:21:in `snap'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/cli.rb:161:in `snap'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/runner.rb:39:in `run_cli'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/lib/do_snapshot/runner.rb:18:in `execute!'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/gems/do_snapshot-1.0.0/bin/do_snapshot:16:in `<top (required)>'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/bin/do_snapshot:22:in `load'
	from /Users/sk/.rvm/gems/ruby-2.4.0@servpro-devops/bin/do_snapshot:22:in `<main>'
```

Any clue what is the problem and how I can fix this?

**Comment by jmcrawford** [comment]
Similar error, Ubuntu 14.04, ruby 2.3.1:

/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:3:in `<class:ResourceCollection>': uninitialized constant ResourceKit::ResourceCollection::Forwardable (NameError)
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:2:in `<module:ResourceKit>'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/resource_kit-0.1.6/lib/resource_kit/resource_collection.rb:1:in `<top (required)>'
        from /root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/gem_ext/resource_kit.rb:19:in `<top (required)>'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter/droplet_kit.rb:4:in `require_relative'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter/droplet_kit.rb:4:in `<top (required)>'
        from /root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter.rb:13:in `const_defined?'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/adapter.rb:13:in `api'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:102:in `api'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:144:in `load_droplets'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:133:in `work_with_droplets'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/command.rb:21:in `snap'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/cli.rb:161:in `snap'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/runner.rb:39:in `run_cli'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/lib/do_snapshot/runner.rb:18:in `execute!'
        from /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/do_snapshot-1.0.0/bin/do_snapshot:16:in `<top (required)>'
        from /root/.rbenv/versions/2.3.1/bin/do_snapshot:23:in `load'
        from /root/.rbenv/versions/2.3.1/bin/do_snapshot:23:in `<main>'

**Comment by merqlove** [comment]
Oops. I will fix it asap. Seems it's caused by my monkey patch of resource_kit. This library still don't have full support for ruby 2.4.
Please use 0.6.4 till fix.

**Comment by merqlove** [comment]
Fixed, checked from OSX.
