### ISSUE TITLE
Digital Ocean API V2 support

### ISSUE THREAD

**Issue by merqlove** [merqlove/do_snapshot#4]
Must be via https://github.com/digitalocean/droplet_kit

**Comment by FrancoisMartin** [comment]
Good idea !

**Comment by FrancoisMartin** [comment]
Digital Ocean is sunsetting API v1 on November 1st 2015.
I have no competences in Ruby to port the code with the new API (https://developers.digitalocean.com/documentation/v2), but if someone has, feel free !

**Comment by merqlove** [comment]
I'm started this work with refactoring into modular application structure. Tests for moved V1 works well, now i'm stuck on V2 and `faraday` gem version between old one and new one API gems. motdotla/digitalocean#47

**Comment by merqlove** [comment]
For now problem solved. Fighting with tests :)

**Comment by FrancoisMartin** [comment]
Nice !!

**Comment by merqlove** [comment]
Released now.

**Comment by FrancoisMartin** [comment]
Good job ! :) I will test it soon.
