### ISSUE TITLE
All Works Flawless Except The Email Dont Want To

### ISSUE THREAD

**Issue by nateisch** [merqlove/do_snapshot#6]
Actually, that was a lie. I didn't tried that part with the cronjob. I always entered the command line into the terminal and I tried a lot to solve the problem by my own, but I don't get it. All works flawless but always at the end (when the email should be sent), I get an error: 

```
Sending e-mail notification.
getaddrinfo: Name or service not known
```

Actually it is a bit longer but every line just starts with `from` + PATH + `open` or `tcp_socket` or `block in do_start` and so on. If you need I can take a screenshot of the whole error message.

This is the actual command I use:

```do_snapshot -p 2 --only 6269613 -k 3 -c -m to:TO from:FROM -t address:HOST user_name:LOGIN password:PASSWORD port:587 -v ```

These are the infos from my mailing server:

Option | Value
--------- | ----------
Protocol/Method |	IMAP
Mail server| mydomain.com
IMAP |Port	993
IMAP Security|	SSL
SMTP Port|	587
SMTP Security|	STARTTLS (“always” or “required”, if prompted)
Username:|	Your whole email address.
Password:|	Your mail password.

For HOST I used `mydomain.com` first, but I think it should be the IP itself.

Thanks in advance!

**Comment by merqlove** [comment]
Hello, 
Will be good, if you can provide full log.
You sure that you have access to that smtp?

**Comment by nateisch** [comment]
Okay, that is the output in the terminal. I can't really format it that good here, sorry for that. And my screen on the laptop here is to small to make good screenshot... :sob: 

````
Start performing operations
Loading list of DigitalOcean droplets
Checking DigitalOcean Access Token.
Setting DigitalOcean Access Token.
Droplet id: 6269613 name: forum Preparing droplet id: 6269613 name: forum to take snap
For droplet with id: 6269613 and name: forum the maximum number 3 of snapshots is reac
Working with list of DigitalOcean droplets
Shutting down droplet.
Event Id: 57798636
Start creating snapshot for droplet id: 6269613 name: forum.
Wait until snapshot will be created.
Event Id: 57798671
Snapshot name: forum_2015_07_26 created successfully.
Droplet id: 6269613 name: forum snapshots: 4.
For droplet with id: 6269613 and name: forum the maximum number 4 of snapshots is reached.
Cleaning up snapshots for droplet id: 6269613 name: forum.
Snapshot: 12900180 delete requested.
All operations has been finished.
Sending e-mail notification.
getaddrinfo: Name or service not known
/usr/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize'
/usr/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
/usr/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
/usr/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
/usr/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/usr/lib/ruby/2.2.0/timeout.rb:99:in `call'
/usr/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
/usr/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
/usr/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
/home/nate/.gem/ruby/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/nate/.gem/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
/home/nate/.gem/ruby/2.2.0/gems/pony-1.11/lib/pony.rb:176:in `deliver'
/home/nate/.gem/ruby/2.2.0/gems/pony-1.11/lib/pony.rb:166:in `mail'
/home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/mail.rb:56:in `call'
/home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/mail.rb:56:in `notify'
/home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/command.rb:19:in `snap'
/home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/cli.rb:161:in `snap'
/home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/runner.rb:34:in `run_cli'
/home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/runner.rb:13:in `execute!'
/home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/bin/do_snapshot:15:in `<top (required)>'
/home/nate/.gem/ruby/2.2.0/bin/do_snapshot:23:in `load'
/home/nate/.gem/ruby/2.2.0/bin/do_snapshot:23:in `<main>'
Sending e-mail notification.
/usr/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /usr/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
	from /usr/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
	from /usr/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
	from /usr/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /usr/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /usr/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /usr/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
	from /usr/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
	from /home/nate/.gem/ruby/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
	from /home/nate/.gem/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
	from /home/nate/.gem/ruby/2.2.0/gems/pony-1.11/lib/pony.rb:176:in `deliver'
	from /home/nate/.gem/ruby/2.2.0/gems/pony-1.11/lib/pony.rb:166:in `mail'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/mail.rb:56:in `call'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/mail.rb:56:in `notify'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/cli.rb:219:in `send_error'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/cli.rb:184:in `error_with_backtrace'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/cli.rb:166:in `rescue in snap'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/cli.rb:161:in `snap'
	from /home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/nate/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/runner.rb:34:in `run_cli'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/lib/do_snapshot/runner.rb:13:in `execute!'
	from /home/nate/.gem/ruby/2.2.0/gems/do_snapshot-0.3.0/bin/do_snapshot:15:in `<top (required)>'
	from /home/nate/.gem/ruby/2.2.0/bin/do_snapshot:23:in `load'
	from /home/nate/.gem/ruby/2.2.0/bin/do_snapshot:23:in `<main>'
````

I have acces to the smtp. Just tried it again to be sure.

**Comment by merqlove** [comment]
@nateisch It's ok. I will try it at my side :+1: 
Your smtp is from Gmail?

**Comment by nateisch** [comment]
@merqlove Its "my own" - its @mail-in-a-box from @JoshData.

**Comment by merqlove** [comment]
@nateisch Just tried mail via Mandrill with same `cmd`. No problem found. Seems that your smtp server really not visible from machine with do_snapshot. Maybe you need additional options, like enable_starttls_auto. But getaddrinfo: Name or service not known always refer to DNS.

```
do_snapshot  -p 2 --only 6301176 -k 1 -c -m to:___ from:___ -t address:smtp.mandrillapp.com user_name:___ password:___ port:587 -v
```

Simple SMTP example:
        :address        => 'smtp.yourserver.com',
        :port           => '25',
        :user_name      => 'user',
        :password       => 'password',
        :authentication => :plain, # :plain, :login, :cram_md5, no auth by default
        :domain         => "localhost.localdomain" # the HELO domain provided by the client to the server

Gmail options example (with TLS/SSL):
        :address              => 'smtp.gmail.com',
        :port                 => '587',
        :enable_starttls_auto => true,
        :user_name            => 'user',
        :password             => 'password',
        :authentication       => :plain, # :plain, :login, :cram_md5, no auth by default
        :domain               => "localhost.localdomain" # the HELO domain provided by the client to the server

**Comment by nateisch** [comment]
Maybe @JoshData can help. I tried with `authentication` and `enable_starttls_auto`. Hmm. I just tried to `telnet` the server. Shouldn't I be able to do that? Seems like the server blocks my connection.

**Comment by JoshData** [comment]
Please don't at-mention me for technical support. Post a message on the Mail-in-a-Box forum if you need help. :-)

**Comment by nateisch** [comment]
Oh, sorry didn't know that. I will do that. Thanks in advance!

**Comment by merqlove** [comment]
@nateisch  Yeah, if you can telnet to the smtp server, you will able to send mail from it.

**Comment by merqlove** [comment]
@nateisch I will close this thread. Seems that this is not do_snapshot issue. But you can always open it.
