### ISSUE TITLE
Error when create a snapshot

### ISSUE THREAD

**Issue by edit-michael** [merqlove/do_snapshot#8]
Hi,

all days ago the gem works correct but today i have an error:

"Droplet is still running.
exception class/object expected
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.1/lib/do_snapshot/adapter/digitalocean_v2.rb:72:in `raise'
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.1/lib/do_snapshot/adapter/digitalocean_v2.rb:72:in `rescue in create_snapshot'
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.1/lib/do_snapshot/adapter/digitalocean_v2.rb:67:in `create_snapshot'
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.1/lib/do_snapshot/command.rb:59:in `create_snapshot'
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.1/lib/do_snapshot/command.rb:136:in `block in thread_runner'"

**Comment by merqlove** [comment]
Hello @edit-michael 
Ok, thanks for report, i will look into.

**Comment by merqlove** [comment]
fixed in 0.3.2

**Comment by edit-michael** [comment]
Hi merqlove,
i tested the version 0.3.2 and have one error more:

Wait until snapshot will be created.
Droplet id: XXX is Failed to Snapshot.
Droplet XXX is still running. Skipping.
undefined method `id' for #<String:0x000000031a0970>
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.2/lib/do_snapshot/adapter/digitalocean_v2.rb:68:in `create_snapshot'
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.2/lib/do_snapshot/command.rb:63:in `create_snapshot'
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.2/lib/do_snapshot/command.rb:139:in `block in thread_runner'
