### ISSUE TITLE
undefined method id

### ISSUE THREAD

**Issue by edit-michael** [merqlove/do_snapshot#9]
Hi merqlove,
i tested the version 0.3.2 and have one error more:

Wait until snapshot will be created.
Droplet id: XXX is Failed to Snapshot.
Droplet XXX is still running. Skipping.
undefined method id' for #<String:0x000000031a0970> /usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.2/lib/do_snapshot/adapter/digitalocean_v2.rb:68:increate_snapshot'
/usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.2/lib/do_snapshot/command.rb:63:in create_snapshot' /usr/local/rvm/gems/ruby-2.1.3/gems/do_snapshot-0.3.2/lib/do_snapshot/command.rb:139:inblock in thread_runner'

**Comment by merqlove** [comment]
#8

**Comment by merqlove** [comment]
I fixed errors, but...
Seems that something changed in DigitalOcean.
We have this error after shutdown because event respond status is `complete`, but droplets still `active`.
When i have to run command twice(with sure that droplets state is `off`) snapshot was created.
I will fix this asap.

**Comment by merqlove** [comment]
Yeah, seems that it fixed in 0.3.4.
I did shutdown by droplet status instead of event

**Comment by edit-michael** [comment]
It works now! Thank you!!

**Comment by merqlove** [comment]
:+1: `Star` if you like it :)
